language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.12
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1


install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt


script:
  - pytest --cov-report term --cov='django_marshmallow' tests/ -v

after_success:
  - coveralls