language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0


install:
  - pip install -r requirements-test.txt


script:
  - coverage run --source='django_marshmallow' pytest

after_success:
  - coveralls