# Generated by Django 2.2.11 on 2020-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_related_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='related_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(null=True, to='blog.Tag'),
        ),
    ]
