# Generated by Django 2.2.11 on 2020-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200424_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
