# Generated by Django 2.2.11 on 2020-04-28 23:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200424_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[blog.models.validate_category_name]),
        ),
    ]
